name: Feature Request
description: Propose a new feature or improvement
title: "[Feature] "
labels:
  - enhancement
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        感谢你的建议。请尽量描述清楚业务场景与验收标准。

  - type: textarea
    id: problem
    attributes:
      label: 背景与痛点
      description: 当前问题是什么，为什么需要这个功能
      placeholder: |
        当前...
        导致...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 建议方案
      description: 希望如何实现
      placeholder: |
        建议新增...
        交互流程为...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 可选替代方案
      description: 是否有其它可行方案

  - type: checkboxes
    id: scope
    attributes:
      label: 影响范围
      options:
        - label: 商品模块
        - label: 任务模块
        - label: 聊天模块
        - label: 求购/订单
        - label: 动态/积分/维基
        - label: 工程与基础设施

  - type: textarea
    id: acceptance
    attributes:
      label: 验收标准
      description: 明确可验证的完成条件
      placeholder: |
        - [ ] 条件1
        - [ ] 条件2
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: 提交前检查
      options:
        - label: 我已搜索过现有 Issue，确认不是重复建议
          required: true
